os: linux
dist: xenial

services:
  - xvfb

addons:
  firefox: latest

branches:
  only:
  - master
  - major
  - stable
  - latest
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^release\/\d+\.\d+\.x$/

language: node_js
node_js:
  - 12

cache:
  npm: false

before_install:
  - 'export DISPLAY=:99.0'
  - npm install npm@7 -g
  - npm --version
install:
  - npm install
script:
  - ng test
env:
  global:
    - secure: nbn1MJ/N+shUkYqXqKxzQJw30F8q7XC4LNxuMYuP13deUI1/XzRWh7l6+T37AVQicDoVXbro2ve5hknc5TtGwGJTZnvZRtnGe/vZigj/N/NGYeuiNSNIzNQ9MyqJ0sxvuPEIDhYn5UfXkpweoYFe4Budy4AWvHbeE8KNLfzs4M+YD/Oyi+dyBY+RvWWHYRgfbrc7ZiDoRcx2ZDeYPjs5gWDK0VfG13IIp3YnZIpL8CWjI0+p1BBzTP9eQxtRcumLlxq1Rm7sqtxyyRaFTLgk1eRp/JdPFeRuMsSDTfNNhORTqgNyFeubWIy7LjzxZ6fZr+fLAVUJwncunFnOo6yAV5qe+kvzAepcli43zM9sdJPUn6FRm2fcQtSccW44rHH2HHaaQd0yg0DIbrBB3n6we3kBzyM/N24Y4Z6kU9rpmJvZTcW9GTjfb9zQzhyinsHPfTlNoTPnPc6ae9Kqudc/f7PboThwfML6t+p/beOHsXZfrHaDGRvzwWQrD8VBaUAhEA7ez4aiVmVSaTKY4Or/BJNMj/fkvWsFidFGFHgyOO9k3YE9ibK0tJBTja6UiuqBOG+7IpcfHkArtAeXXvTMS8ON1wUc0HMWSsEVYiNjiLP8rLlnNek5McZT5VondvpqvFzMtU/d3ONL/AQ4XbZSiJetBVQDmzgqgKDcJmW6PZo=
    - secure: QHLviMCt0OLmb8mYOdZ2v2Dm/+PRtbOJ6et7C3/tu3Wt0in+RnQap1pXbN9Pz8Vgsd1AbAL5VAmZaKKI6YNLHmdDnHq15piTLYUWInkEIW26ypLas+KJ4II4Az4QWZSimvXgkAogu7dPgH22fAQB+oRQsrw9ZkJWlzEYzl4z2I7hnyH8zkssxwQ7GhjCliiivVEY5jVDSUMV8STH1qOhL1LRDgWSTYPd1qDiJ80KEGKijRyerid85NXVZgIVU94BpRHmNi1bgnE2vUaDkTHv+eY2Cv6W+J2ZhqfMxtoBoqhbDe1gEJjNl79mPP6b61yAJdfDXOcdO+vMmbaj6DYr8H/Hz1O43AeHdjIrkFTIATMstqndlJ88tkiFVFRWWk2iK3PV1gquU11LZjZ/6HK8xVtZRojaODcBcU4RwvCFUYnwKAKM+UVYYEU0vmhR38C1O8U6O4KDrI01TxV6WidgyNGlqDjmPyESNBvJMTsNB75iRsCczn+v1pwLyVLrdrPInDtdXnBh/5LnwbNEFpf9g6L3XQl9HYgfev3O+Ci+6c0Sz4GCvS41vs2afXWmoARSBGFPBLSTtNIMtVJ2VlOXxcOPOPTbpzYjgs8KOqXQvYtYJp0cKWChuerdKBNu5p5/c1l1IDTTfOIdDD1oXvA9FJaCmAEZtU6GJ1in9DjDeSw=
    - secure: "IILdw06Lz8oHC9HMtQvL7Vc6h+pK4A4BLXsPAR8T48XbBoSOVQXv8kho+Zo9i+NPz/flRFkHrxTsGFwCG/L+wN8dNsrXKFzceETZwD9PV3LF+xpsfHYAGD2Utzwnq5/NhtMR7mUkwj4s728k+jn9a9iJ59uNARMT/yGYVAweZQbN1RvH3uzN5LQQozoCnXAlpDWV1dUkgeqsCd8TbfGcjKjbHPIXtazeQHeNw73xoza21rsDIGvsTdVYjDR33Fy1fCxqjwhsakKL8iv2y48wshbHE36oe27Fr7CiV+4JeLlNAZvAkHObj+KzEvHtOkBBaJnq+Yw18bJQw3qpp+kwYO8E415H7iVg6z2zMORRR/7vQ+gbyazUICICTZHXsb+0Uy4ElgFqdef/qRIw0A9GIEnlD2GVdsLqCp1IBGeYjh3lAmjpuMk4zXy1iBoZZENHo6szKdntQM+wuI9S2cRBeRZTG2CLnGs/ri/wwYk4sEDEHnbSrExseKHfrB7brribVb0vVoLQzvPyRHFzJB/gACNE5CJ7UYrCVLZt2RtjhyPzDqeJJ9T4jSFDVRcQlkb5pbe5mKvLiqx2zBt/Eq0pNoujK20M8ed9xdMUnja1PpeRfcIA5rURGi0MLXeXFfu9HbkHkWvFPXRiR+m1Yo4UmX1lE4fCLu1c3mr/jGwwhdk="
